export const BUDDY_CONNECTION = 'BUDDY_CONNECTION';
export const BUDDY_CLIENT = 'BUDDY_CLIENT';
export const BUDDY_MINTS = 'BUDDY_MINTS';
export const BUDDY_ORGANIZATION = 'BUDDY_ORGANIZATION';

export const BUDDY_PROFILE = 'BUDDY_PROFILE';
export const BUDDY_MEMBERS = 'BUDDY_MEMBERS';
export const BUDDY_STATS = 'BUDDY_STATS';
export const BUDDY_TREASURIES = 'BUDDY_TREASURIES';
export const BUDDY_OPTIONS = 'BUDDY_OPTIONS';
export const BUDDY_PUBLIC_KEY = 'BUDDY_PUBLIC_KEY';